# permissions for end users to view redisconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redisconnection-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: zncdata-stack-operator
    app.kubernetes.io/part-of: zncdata-stack-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisconnection-viewer-role
rules:
- apiGroups:
  - stack.zncdata.net
  resources:
  - redisconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stack.zncdata.net
  resources:
  - redisconnections/status
  verbs:
  - get
