apiVersion: stack.zncdata.net/v1alpha1
kind: DatabaseConnection
metadata:
  labels:
    app.kubernetes.io/name: databaseconnection
    app.kubernetes.io/instance: databaseconnection-sample
    app.kubernetes.io/part-of: zncdata-stack-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: zncdata-stack-operator
  name: databaseconnection-sample-postgres
spec:
  default: true
  provider:
    driver: postgres
    host: localhost
    port: 5432
    ssl: false
    credential:
        username: root
        password: "123456"
  # TODO(user): Add fields here
